### ISSUE TITLE
「评论」Vite快速搭建Vue3+TypeScript项目

### ISSUE THREAD

**Issue by coderlyu** [coderlyu/au-blog#22]
页面：https://coderly.cn/pages/33b18f/

**Comment by wei-jc** [comment]
666666

**Comment by daimingbao** [comment]
牛

**Comment by rantrism** [comment]
您好～我是腾讯云+社区的运营，关注了您在分享的技术文章，觉得内容很棒，我们诚挚邀请您加入腾讯云自媒体分享计划。完整福利和申请地址请见：https://cloud.tencent.com/developer/support-plan
作者申请此计划后将作者的文章进行搬迁同步到社区的专栏下，你只需要简单填写一下表单申请即可，我们会给作者提供包括流量、云服务器、域名等，另外还有些周边礼物。  我们诚挚的邀请您并期待您的加入~
腾讯云+社区是由腾讯云全新打造的一个技术交流社区，正在引入更多的作者与优质文章，就此社区推出一个自媒体的分享计划。
